all implementation with MIN and MAX as boundaries/searchbars for the …
studhub-epfl/studhub-app pull request #103
Opened 2023-04-21 04:05 UTC by tepoorte

…object with the price in that boundaries, associated tests and new classes, and associated changes in BrowseScreen and BrowseViewModel

2023-04-21 06:58 UTC, edouardmichelin requested changes
Some major elements would need to be refactored.
Also CI is failing

2023-04-21 06:58 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +    private var l = mutableListOf<Listing>()
I'm sure that we can find a better (more explicit) name for this one

2023-04-21 06:58 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +
I think it would have been better to somehow do it all in one method.
This looks a bit big and repetitive

2023-04-21 06:58 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +
Also what if `getListingsByMax` is called before `getListingsByMin`, as `getListingsByMax` seems to require that `l` is populated.
Even though you call them in order, co-routines are executed in parallel so there could be re-ordering or interleaving.

2023-04-21 06:58 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseViewModel.kt
> +
There is no precedence here (comment related to the previous ones)

2023-04-21 06:58 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/listing/browse/components/MaxSearch.kt
> +}
The only difference between `MinSearch` and `MaxSearch` is the name and the text values `""MIN....CHF""` and `"MAX....CHF"`.
I think it would have been a better idea to have a more generic component which takes (for example) a `label` as parameter.

2023-04-21 06:58 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/listing/browse/components/SearchBar.kt
> -                //},
Remove unnecessary comments

2023-04-25 15:18 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +
The reason why I didn't is because to be able to create a good fit with the price range using two inputs it would have been much more complicated to do it in one method, so I thought rather to use an intersection method: x>A, x<B-> A<x<B

2023-04-25 15:20 UTC, tepoorte commented on app/src/main/java/com/studhub/app/presentation/listing/browse/components/MaxSearch.kt
> +}
I completely agree with that.

2023-04-25 15:22 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +
The main issue to solve, is what you wrote in the second comment. I'm working on it.

2023-04-25 15:24 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +    private var l = mutableListOf<Listing>()
Absolutely, as also the commenting part should be improved.

2023-05-01 22:57 UTC, NervzZ requested changes
Minor change required as per the comments. Otherwise it should be good and if the local coverage you have is decent then we can approve on your next update.

2023-05-01 22:57 UTC, NervzZ commented on app/src/main/java/com/studhub/app/domain/repository/ListingRepository.kt
> +    /**00
Seems like you left a typo

2023-05-01 22:57 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/components/RangeBar.kt
> +}
Massive composable.
You can easily split your bar in multiple different composables such as at least making one for your OutlinedTextField.
It allows you to pass parameter to these composables if they depend on some and makes testing even easier as you can test these composables one by one.

For the sake of readability too, please try your best to modularise as said above.

2023-05-01 22:57 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/components/SearchBar.kt
> +    search: MutableState<String> = remember { mutableStateOf("") },
As said before, consider using rememberSaveable instead

2023-05-02 00:34 UTC, NervzZ approved these changes
After my requested changes it looks good to me, if you're convinced about your coverage and functionality then we can approve this.

2023-05-02 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/components/RangeBar.kt
> +package com.studhub.app.presentation.ui.common.input
This file looks much better after my requested changes, good job!

2023-05-02 11:28 UTC, raynasr approved these changes
After discussions on discord and Julien's request changes, all LGTM.

2023-05-02 14:42 UTC, merged