Feature/issue 95 blocking
studhub-epfl/studhub-app pull request #105
Opened 2023-04-21 07:38 UTC by Edouard-6

2023-04-21 07:50 UTC, tepoorte requested changes
There are some conflicts that must be adjusted before merging

2023-04-27 15:13 UTC, raynasr requested changes
LGTM, requires testing

2023-04-27 19:55 UTC, raynasr approved these changes
LGTM.

2023-04-27 19:58 UTC, tepoorte approved these changes

2023-04-27 19:59 UTC, merged