Internal functionnalities for report feature
studhub-epfl/studhub-app pull request #106
Opened 2023-04-21 07:38 UTC by Edouard-6

2023-04-27 15:11 UTC, raynasr requested changes
Well structured! Just needs tests.

2023-04-30 18:15 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ReportRepositoryImpl.kt
> +                emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
To be clearer, at some point in time, we should for example consider different scenarios: for example, It would be helpful to handle other types of exceptions that might occur during the execution of the code. For instance, a network error or a database error could occur, and it would be good to handle them and notify the user appropriately.

2023-04-30 18:15 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ReportRepositoryImpl.kt
> +
you could replace the forEach, I would do something like this: 
_override suspend fun getReportsForItem(itemId: String): Flow<ApiResponse<List<Report>>> = flow {
    emit(ApiResponse.Loading)
    val query = db.orderByChild("reportedItemId").equalTo(itemId).get()
    query.await()
    if (query.isSuccessful) {
        val reports = query.result.children.mapNotNull { snapshot ->
            snapshot.getValue(Report::class.java)
        }
        emit(ApiResponse.Success(reports))
    } else {
        val errorMessage = query.exception?.message.orEmpty()
        emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
    }
}_

2023-04-30 18:15 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ReportRepositoryImpl.kt
> +
Also don't forget code repetitions, for the code climate. Otherwise, as I said, it looks good to me

2023-05-04 20:41 UTC, raynasr approved these changes
Approved

2023-05-05 03:54 UTC, merged