Feature/issue 91 finish messaging system
studhub-epfl/studhub-app pull request #119
Opened 2023-04-28 03:33 UTC by edouardmichelin

Finished implementing the messaging part.
Conversation are created by clicking the "contact seller" button on any product page.
The app then navigates to the conversation, which can be found back later when going to the conversations page from the hope page.
Conversations and messages inside a conversation are automatically updated as messages and conversations are created.

UI is not tested yet.

2023-04-30 00:34 UTC, NervzZ requested changes
Nicely done overall, this is already looking good for a chat system.
Minor changes requested for this to go through and I would also like to know how is the test coverage of that code since the coverage report is missing.

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/NavigationComponent.kt
> +            Globals.showBottomBar = false
Nicely done, it's more robust and easier to chose whether the navbar should be visible or not directly here.

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/NavigationComponent.kt
> +            ChatScreen(conversationId = id, navigateBack = { navController.popBackStack() })
Commenting that part would be nice just to make it clearer how it works.

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/data/repository/ConversationRepositoryImpl.kt
>                  emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
Shouldn't the error message be a little more explicit to add some context?

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/data/repository/MessageRepositoryImpl.kt
> +            trySend(ApiResponse.Loading)
Good catch removing the blocking ones, makes the app usage much better.

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/conversation/ChatScreen.kt
> +import androidx.compose.material3.*
Thank you for fixing that xD

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/conversation/components/ConversationItem.kt
> +    return text.take(limit) + if (text.length > limit) ellipsis else ""
This is nice to have. We could limit it to something quite a big bigger than 40 for our current conversations though.

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/conversation/components/MessageCard.kt
> +                .background(color = MaterialTheme.colorScheme.background)
These seem to be the chat text bubbles so it will not look good if you set the background to that color. Instead use `secondary` or `tertiary` (or even `secondaryContainer` or `tertiaryContainer`) to add a nice color to these and allow the conversation background to be set to `background`.

Also change the text color to use something like `onSecondary` (based on your color usage) so that it's always readable over the used color scheme.

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingScreen.kt
> +            Spacer("large")
Nice one, I learned something.

2023-04-30 00:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingScreen.kt
> -}
Why remove the preview?

2023-05-02 11:51 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/conversation/ChatScreen.kt
> +                        BasicFilledButton(onClick = navigateBack, label = "<")
In the future consider extracting the label "<"  or w/e into a string resource or a constant

2023-05-02 11:52 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/conversation/ChatScreen.kt
> +                        BigLabel(label = viewModel.conversation!!.user2Name)
in the future consider handling the case when viewModel.conversation is null to prevent potential null pointer exceptions (using elvis operator ?)

2023-05-02 11:52 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/conversation/ChatViewModel.kt
> +                    is ApiResponse.Success -> {}
Circular loading maybe?

2023-05-02 11:53 UTC, raynasr approved these changes
A few minor suggestions otherwise ready to merge.

2023-05-02 14:51 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingScreen.kt
> +            Spacer("large")
This is a custom spacer, not the one from material UI ;)

2023-05-02 14:54 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/conversation/ChatScreen.kt
> +                        BasicFilledButton(onClick = navigateBack, label = "<")
Sure thing, I forgot this one

2023-05-02 16:07 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/conversation/ChatViewModel.kt
> +                    is ApiResponse.Success -> {}
Not when a message is being sent. However we could maybe indicate the status on the message box (loading => no check mark, sent => check mark)

2023-05-02 16:08 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/listing/details/components/StartConversation.kt
> +        is ApiResponse.Failure -> {}
I was actually thinking about a new way to log errors. But it would be in the repository implementation, not here as this part of the code is view-oriented

2023-05-02 16:17 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/data/repository/ConversationRepositoryImpl.kt
>                  emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
Yes, this is more of a placeholder that's here before we decide on a more efficient way to report errors (which I may have found).

2023-05-02 16:19 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/conversation/components/MessageCard.kt
> +                .background(color = MaterialTheme.colorScheme.background)
Sure, will do

2023-05-04 02:54 UTC, edouardmichelin commented
## New chat view
![image](https://user-images.githubusercontent.com/42861545/236100783-8e5e902a-42bf-4a63-b8f3-ab82132114e5.png)

## Regarding tests
![image](https://user-images.githubusercontent.com/42861545/236101774-b410bd6f-969d-443e-a501-864a371216e3.png)
![image](https://user-images.githubusercontent.com/42861545/236101844-bd3ab861-b142-46a3-bf2c-203a31d8921f.png)
![image](https://user-images.githubusercontent.com/42861545/236101946-44c3aa2f-1a1d-4bed-b9e0-268526bccea2.png)

2023-05-04 04:20 UTC, NervzZ requested changes
very minor changes required and we should be good to go

2023-05-04 04:20 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/conversation/components/MessageCard.kt
> +fun MessageCard(conversation: Conversation, message: Message) {
Having the corner facing the user's owner of that message be angular instead of rounded would be a nice effect in mimicking a chat bubble

2023-05-04 04:20 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/ui/common/container/Card.kt
> +}
line return slipped

2023-05-04 04:20 UTC, NervzZ commented on app/src/main/java/com/studhub/app/wrapper/ConversationActivity.kt
> +}
line return again

2023-05-04 05:05 UTC, NervzZ approved these changes
Looks really nice after the changes. Good job on testing and on the messaging system

2023-05-04 06:00 UTC, merged