Feature/maps v2
studhub-epfl/studhub-app pull request #125
Opened 2023-05-04 18:45 UTC by raynasr

Attempting to fix the broken issue-93 branch.

2023-05-04 22:39 UTC, edouardmichelin requested changes
Nicely done overall.
Some points need to be assessed, otherwise good job.

2023-05-04 22:39 UTC, edouardmichelin commented on app/src/androidTest/java/com/studhub/app/presentation/listing/details/DetailedListingScreenTest.kt
> +            onMeetingPointClick = {})
You certainly missed it but the `onMeetingPointClick` parameter is misaligned and the closing parenthesis should be on the next line.
cf. [Kotlin Coding Convention - Functions](https://kotlinlang.org/docs/coding-conventions.html#functions)
![image](https://user-images.githubusercontent.com/42861545/236339348-0a94f4ec-5d1f-4f95-a103-f38a45560ce7.png)
[Kotlin Coding Convention - Method calls](https://kotlinlang.org/docs/coding-conventions.html#method-calls)
![image](https://user-images.githubusercontent.com/42861545/236339589-12cd4ac5-5586-4365-88a7-95fd554cb943.png)

2023-05-04 22:39 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/MeetingPointPickerActivity.kt
> +}
I think this function should either be private or just moved out to a another location.

For instance we could add an `extensions` package in the already existing `com.studhub.app.core` package and put all our extensions here.
This one could be in a file named `IntExtensions` such that the fully qualified name would look something like `com.studhub.app.core.extensions.IntExtensions`.
I think this is an easily maintainable solution but I let you tell me what you think about it.

2023-05-04 22:39 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/MeetingPointPickerActivity.kt
> +}
### File size
This is a pretty big file. Whereas I don't know if you can split it up in multiple smaller files, I think we can still do something to make it more readable.

Android Studio has inherited support for regions from intellij so something you could do is simply separate your file in different regions, let me show you an example:
You start a region named "hello" with `// region hello` and end it with `// endregion`

![image](https://user-images.githubusercontent.com/42861545/236342117-c54be01e-ca95-4d8b-8a05-a7f2bc47cde1.png)

![image](https://user-images.githubusercontent.com/42861545/236342229-e03ed666-a50f-4567-b802-ce35f8faa58f.png)




### String literal
You're using a lot of literal strings here. You should try making use of string resources :)
Just go ahead and create a `strings_map.xml` file in `res/values`

2023-05-04 22:39 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/domain/model/Listing.kt
> +    val meetingPoint: MeetingPoint? = MeetingPoint(1.0,1.0)
Why is the default value `MeetingPoint(1.0, 1.0)` instead of `MeetingPoint(0.0, 0.0)`?
Also why make it nullable if it has a default non-null value?

2023-05-04 22:39 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/listing/add/CreateListingScreen.kt
> +            location?.let { latLng ->
I think `position` (instead of `latLng`) would be a better name but maybe that's just me

2023-05-04 22:39 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingScreen.kt
> +                    Text("View Meeting Point")
String resources ;)

2023-05-05 00:20 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/listing/add/CreateListingScreen.kt
> +            location?.let { latLng ->
Will change

2023-05-05 00:22 UTC, raynasr commented on app/src/main/java/com/studhub/app/MeetingPointPickerActivity.kt
> +}
Will change

2023-05-05 00:24 UTC, raynasr commented on app/src/main/java/com/studhub/app/domain/model/Listing.kt
> +    val meetingPoint: MeetingPoint? = MeetingPoint(1.0,1.0)
Will change

2023-05-05 16:10 UTC, edouardmichelin approved these changes

2023-05-05 16:26 UTC, merged