Implemented  bidding by extending listing structure
studhub-epfl/studhub-app pull request #154
Opened 2023-05-14 19:59 UTC by Edouard-6

Implemented bidding by extending listing structure with tests

2023-05-14 23:45 UTC, raynasr requested changes
Great code, waiting for the //TODO to be completed.

2023-05-14 23:45 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +        if (query.isSuccessful) {
What if an exception occurs while making the setValue call itself? It might be a good idea to wrap the setValue call in a try-catch block to handle potential exceptions.

2023-05-14 23:45 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +import java.util.*
While this is a minor point, , you can use Ctrl + Alt + O to organize your imports.

2023-05-14 23:45 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +        if (!networkStatus.isConnected) {
It's excellent that you're checking for an active network connection before making the API call.

2023-05-14 23:45 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +        if (query.isSuccessful) {
try {
            val query = db.child(listing.id).setValue(biddingListing)

            query.await()

            if (query.isSuccessful) {
                emit(ApiResponse.Success(biddingListing))
            } else {
                val errorMessage = query.exception?.message.orEmpty()
                emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
            }
        } catch (exception: Exception) {
            emit(ApiResponse.Failure(exception.message ?: "Unexpected error"))
        }

2023-05-14 23:45 UTC, raynasr commented on app/src/main/java/com/studhub/app/domain/repository/ListingRepository.kt
> +
Good job with the code comments, they are clear and explain the purpose of the class and its methods well.

2023-05-14 23:45 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/listing/add/FakeListingRepository.kt
> +        TODO("Not yet implemented")
Waiting for this before approving

2023-05-15 11:50 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/presentation/listing/add/FakeListingRepository.kt
> +        TODO("Not yet implemented")
No one is using this FakeListingRepository, I am thinking of deleting it.

2023-05-15 12:15 UTC, raynasr approved these changes
//TODO was fake class which was removed, LGTM now

2023-05-15 14:16 UTC, merged