feature/issue-136-connect-bidding-system-to-backend
studhub-epfl/studhub-app pull request #176
Opened 2023-05-24 22:58 UTC by NervzZ

Finished the bidding system implementations such that :
- We can now properly create bidding listings
- We can place bids on those
- If we currently hold the best bid, it is stated on the listings details, if not we can access the bid controls like any other users.

2023-05-24 22:58 UTC, NervzZ commented
Tests incoming

2023-05-25 13:04 UTC, tepoorte requested changes
Nice work, well done! Just some very little improvements before merging can be done.

2023-05-25 13:04 UTC, tepoorte commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingViewModel.kt
> +                        onError("Your bid needs to be greater than the current one")
Type for currentListing should be explicit, I would avoid using type inference.

2023-05-25 13:04 UTC, tepoorte commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingViewModel.kt
> +                                    is ApiResponse.Loading -> {}
Well done for String.format !

2023-05-25 13:04 UTC, tepoorte commented on app/src/main/java/com/studhub/app/presentation/listing/details/components/BiddingControls.kt
> +    Column(
pay attention for the date format, In the createListing interface we actually have _MM.DD.YYYY_

2023-05-25 13:23 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/details/components/BiddingControls.kt
> +    Column(
Doesn't really matter, that's the default display format on top of the datepicker but we can see the input is in the usual format I'm using to display the date :
![image](https://github.com/studhub-epfl/studhub-app/assets/56892303/5e19b280-9125-4cf3-8a4f-4e77c82c7705)

2023-05-25 13:26 UTC, NervzZ commented on app/src/androidTest/java/com/studhub/app/presentation/listing/details/DetailedListingViewModelTest.kt
> +    }
good catch

2023-05-25 13:27 UTC, NervzZ commented on app/src/androidTest/java/com/studhub/app/presentation/listing/details/DetailedListingScreenMainComposableTest.kt
> +        getFavoriteListings,
It's the only viewmodel of the file and it's a testing file about DetailedListingScreen.

2023-05-25 15:12 UTC, merged