fixed search and search Categories backend
studhub-epfl/studhub-app pull request #177
Opened 2023-05-25 15:55 UTC by tepoorte

2023-05-25 16:34 UTC, NervzZ requested changes
Few minor changes to be done

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +        categoryChoose: List<Category>,
Might want to rename this as "chosenCategories" like we talked about to highlight the fact it's a list.

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
>                              || listing.price.toString().contains(keyword, true))
Remove that one line, keywords should not relate to the pricing of the item.

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/domain/repository/ListingRepository.kt
> +        categoryChoose: List<Category>,
call it chosenCategories for better clarity

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +                        listings.add(listing)
Conditions nesting could be cleaner I think. You need to make sure any of the criterias can be null (we also need to be able to search by specyfing for example a price and nothing else, so empty keyword but min price is one of few possibilities) without creating a huge spaghetti of conditions to check which are null and which aren't to define behaviors for each of the possibilities.

Instead checking whether or not a specific criteria is set by the user WHEN you are about to filter is a smarter approach so you avoid these huge series of and conditions.

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseScreen.kt
> +    val rangeMaxVal = rangeMax.value.takeIf { it.isNotEmpty() } ?: "10000"
10'000 is very small, try using Float.MAX_VALUE instead (or something like that)

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseScreen.kt
>          RangeBar("MIN....CHF", search = rangeMin, onSearch = {
Please remove string literals and call string values from keys instead

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseScreen.kt
>          RangeBar("MAX....CHF", search = rangeMax, onSearch = {
Please remove string literals and call string values from keys instead

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseViewModel.kt
> +                      categoryChoose: List<Category>) {
Might want to name this chosenCategories instead for better clarity

2023-05-25 16:34 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseViewModel.kt
> +            getListingsBySearch(keyword, minPrice, maxPrice,categoryChoose).collect {
don't forget to CTRL + ALT + L your files to format correctly

2023-05-25 16:47 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
>                              || listing.price.toString().contains(keyword, true))
Good catch!

2023-05-25 16:59 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +                        listings.add(listing)
switching more important conditions in first place can be a good solution. Thanks!

2023-05-26 03:36 UTC, Edouard-6 reviewed
LGTM.

2023-05-26 03:36 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +                if (listing != null
Comment this code because it is long and not very self explicit.

2023-05-26 03:36 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseScreen.kt
>          RangeBar("MIN....CHF", search = rangeMin, onSearch = {
Remove string literals please.

2023-05-26 03:36 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/presentation/listing/browse/BrowseScreen.kt
> +    val rangeMaxVal = rangeMax.value.takeIf { it.isNotEmpty() } ?: "10000"
This one has been resolved.

2023-05-26 03:46 UTC, NervzZ approved these changes
LGTM

2023-05-26 04:10 UTC, merged