Feature/issue 8
studhub-epfl/studhub-app pull request #24
Opened 2023-03-10 00:09 UTC by raynasr

Basic home page, browse and listing screens, will be developed later on the project
Testing not required at this moment. 
Please check the code for inconsistencies and take a look at the composition of the buttons / screens.

2023-03-10 00:24 UTC, NervzZ requested changes
See comments for changes, also don't forget about new lines at end of files as it's missing in some of them.

2023-03-10 00:24 UTC, NervzZ commented on app/src/main/java/com/studhub/app/MainActivity2.kt
> +class MainActivity2 : ComponentActivity() {
Activity is better named something like "HomePageActivity"

2023-03-10 00:24 UTC, NervzZ commented on app/src/main/java/com/studhub/app/MainActivity2.kt
> +fun HomePage(onAddListingClick: () -> Unit, onBrowseClick: () -> Unit) {
Don't name this "HomePage", try to split this in smaller components if necessary and just call it "Nav" for example if it contains only buttons leading to other activities.

2023-03-10 00:24 UTC, NervzZ commented on app/src/main/java/com/studhub/app/MainActivity2.kt
> +}
Should not even be here. This content will be inside another activity completely.

2023-03-10 00:24 UTC, NervzZ commented on app/src/main/java/com/studhub/app/MainActivity2.kt
> +}
Should not even be here. This content will be inside another activity completely.

2023-03-10 00:24 UTC, NervzZ commented on app/src/main/res/values/strings.xml
> +    <string name="title_activity_main2">MainActivity2</string>
As said in first comment, rename this to something like HomePageActivity

2023-03-12 18:33 UTC, edouardmichelin requested changes
You need to rebase `master` branch
`HomePageActivity.kt` will need to be better organized i.e.: split into multiple files

2023-03-12 18:33 UTC, edouardmichelin commented on .idea/.name
> -Bootcamp
Remove file

2023-03-12 18:33 UTC, edouardmichelin commented on .idea/deploymentTargetDropDown.xml
>  </project>
Please use Pixel_2_API_33

2023-03-12 18:33 UTC, edouardmichelin commented on app/build.gradle
>      id 'com.google.gms.google-services'
Rebase `master` branch

2023-03-12 19:41 UTC, NervzZ approved these changes
LGTM now

2023-03-12 20:46 UTC, edouardmichelin approved these changes

2023-03-12 20:49 UTC, merged