Feature/bootcamp fragments
studhub-epfl/studhub-app pull request #3
Opened 2023-03-02 14:29 UTC by raynasr

Requesting a review for the Fragments feature.

2023-03-02 15:20 UTC, NervzZ requested changes
Changes requested in first comment.

2023-03-02 15:20 UTC, NervzZ commented on .idea/.name
> +Bootcamp
From this change I see that you did not rebase master. Please go on your branch (bootcamp-fragments) and do git rebase master then push to update this PR. Then I'll review the rest of the PR.

2023-03-02 17:06 UTC, raynasr commented on .idea/.name
> +Bootcamp
Thank you, it had slipped my attention.

2023-03-02 19:37 UTC, edouardmichelin requested changes

2023-03-02 19:37 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/GreetActivity.java
> +        String message = String.format("Hello my dear %s, how are you?", name);
intentionnel

2023-03-03 00:25 UTC, NervzZ approved these changes
Outside of what Edouard said it looks ok to me. I may ask you a few questions about fragments for my own understanding of the code itself though.

2023-03-12 03:18 UTC, closed without merging