Feature/issue 12
studhub-epfl/studhub-app pull request #43
Opened 2023-03-14 20:07 UTC by tepoorte

2023-03-15 00:41 UTC, Edouard-6 requested changes
Overall, the code looks good and well-structured.
Need to make small changes.

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +                emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
It is better do refactor the 2 lines above which are used 3 times in this class and make a method instead that takes a query as parameter and call this method in these 3 cases.

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +}
Add newline at end of file.

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/test/java/com/studhub/app/ListingRepositoryImplTest.kt
> +}
Add newline at end of file.

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/test/java/com/studhub/app/ListingRepositoryImplTest.kt
> +    fun `Test if it's correctly added on firebase database`() {
If you want to leave this test as it is, don't use '' and change its name to `testAddingValuesToFirebaseDatabase()`

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/test/java/com/studhub/app/ListingRepositoryImplTest.kt
> +               val value = dataSnapshot.getValue<ArrayList<String>>()
Add an `assertEquals(myList, value)` after retrieving the value from the database

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +import com.google.android.gms.common.api.Api
Remove import not used

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +        val listingToPush: Listing = listing.copy(id = listingId)
As a convention, avoid verbs as variable names, use `pushedListing` instead.

2023-03-15 00:41 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +            //val retrievedListing: Listing? = query.result.getValue(Listing::class.java)
Did you forget to remove this comment? If yes remove it.

2023-03-15 14:42 UTC, raynasr requested changes
Remove useless import and add constant variable

2023-03-15 14:42 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +                emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
Consider using a constant for the default error message "Firebase error" to avoid repeating it.

2023-03-15 14:42 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +                emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
private val defaultFirebaseErrorMessage = "Firebase error"
add this after db first line

2023-03-15 14:42 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +        val listingToPush: Listing = listing.copy(id = listingId)
listingToPush looks better for me, since listing being the first word makes it clearer

2023-03-15 15:37 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +        val listingToPush: Listing = listing.copy(id = listingId)
I get what you said @Edouard-6, however here the verb is not used in a declarative manner.
But the name can indeed be ambiguous; a middle ground would be `listingToBePushed`

2023-03-15 15:42 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +                emit(ApiResponse.Failure(errorMessage.ifEmpty { "Firebase error" }))
I think we will start using `R.string` (from `strings.xml`) in sprint 2 and this file will be part of the refactor

2023-03-15 19:51 UTC, raynasr approved these changes
good

2023-03-15 21:59 UTC, Edouard-6 approved these changes
LGTM

2023-03-16 00:40 UTC, Edouard-6 approved these changes

2023-03-16 00:40 UTC, Edouard-6 commented on app/src/test/java/com/studhub/app/ListingRepositoryImplTest.kt
> +}
Add newline at end of file

2023-03-16 01:42 UTC, merged