Feature/issue 18
studhub-epfl/studhub-app pull request #44
Opened 2023-03-15 13:51 UTC by raynasr

Listing Screen isn't accessible from Navigation yet (we will implement it once we have actual listings to browse to.) Fake listing present to test in NavController. Set destination to "Listing".
Added tests for every screen.
Home now has 4 buttons: Add Listing (different from Listing), Cart, About, Browse.
Developed NavigationTest further

2023-03-15 14:56 UTC, tepoorte approved these changes
It looks good to me, still you can add some private methods in order to make the code more understandable for each screen

2023-03-16 02:16 UTC, edouardmichelin requested changes
Added some comments. Otherwise LGTM

2023-03-16 02:16 UTC, edouardmichelin commented on app/src/androidTest/java/com/studhub/app/ui/ListingScreenTest.kt
> +            id = 1,
The `id` field is not a `String`

2023-03-16 02:16 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/ui/ListingScreen.kt
> +                    text = "$${listing.price}",
Prices will be in CHF ;)

2023-03-16 02:16 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/ui/ListingScreen.kt
> +                  onFavouriteClick: () -> Unit) {
Weird alignment, I think the following would look nicer:
```kt
fun listingScreen(
    listing: Listing,
    onContactSellerClick: () -> Unit,
    onFavouriteClick: () -> Unit
) {
    // code
}
```

2023-03-16 02:16 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/ui/ListingScreen.kt
> +                  onFavouriteClick: () -> Unit) {
![image](https://user-images.githubusercontent.com/42861545/225491164-55edafd9-4709-4fd5-8dc5-0621f6c94706.png)

cf this from [https://kotlinlang.org/docs/coding-conventions.html#functions](https://kotlinlang.org/docs/coding-conventions.html#functions)

2023-03-16 02:16 UTC, edouardmichelin commented on app/src/androidTest/java/com/studhub/app/ui/ListingScreenTest.kt
> +        composeTestRule.onNodeWithText("$${listing.price}").assertIsDisplayed()
Don't forget to also modify the dollar sign from the test if you modify it in the other class

2023-03-16 12:59 UTC, raynasr commented
Changes done

2023-03-16 17:27 UTC, edouardmichelin requested changes
Just a minor change, otherwise LGTM

2023-03-16 17:27 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/ui/ListingScreen.kt
> +)
`CTRL + ALT + L` ;)

2023-03-16 17:27 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/ui/ListingScreen.kt
> +)
The offset seems a bit large

2023-03-16 17:32 UTC, edouardmichelin approved these changes
All good

2023-03-16 18:28 UTC, merged