Feature/issue 56
studhub-epfl/studhub-app pull request #73
Opened 2023-03-20 13:07 UTC by raynasr

Refactored the entire UI structure. 
Check presentation and presentation.ui
Check usecase.user

2023-03-21 17:15 UTC, edouardmichelin requested changes
Some files need to be removed.
Some changes are requested regarding conventions and project architecture.
Otherwise good job!

2023-03-22 05:13 UTC, edouardmichelin commented
Such a big PR goes against all my beliefs but its purpose is to refactor a big part of the project and it had to be done

2023-03-22 17:40 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/presentation/home/HomeScreen.kt
> +            WelcomeText(viewModel = viewModel)
I agree with you that we can do some exceptions, for example like here and pass the viewModel directly.

2023-03-22 17:43 UTC, Edouard-6 commented on app/src/main/res/values/strings_about.xml
> +</resources>
Add newline at end of file.

2023-03-22 17:44 UTC, Edouard-6 commented on app/src/main/res/values/strings_home.xml
> +</resources>
Add newline at end of file.

2023-03-22 17:44 UTC, Edouard-6 commented on app/src/main/res/values/strings_listings.xml
> +</resources>
Add newline at end of file.

2023-03-22 17:44 UTC, Edouard-6 commented on app/src/main/res/values/strings_misc.xml
> +</resources>
Add newline at end of file.

2023-03-22 17:44 UTC, Edouard-6 commented on gradle.properties
> -org.gradle.configureondemand=true
Add newline at end of file.

2023-03-22 19:54 UTC, merged