Feature/issue 71
studhub-epfl/studhub-app pull request #77
Opened 2023-03-28 19:37 UTC by edouardmichelin

2023-03-28 23:56 UTC, NervzZ requested changes

2023-03-28 23:56 UTC, NervzZ commented on app/src/androidTest/java/com/studhub/app/NavigationTest.kt
> +        composeTestRule.onNodeWithText(str(R.string.auth_title)).performClick()
Seems like you forgot to actually test what you wanted.

2023-03-29 00:37 UTC, edouardmichelin commented on app/src/androidTest/java/com/studhub/app/NavigationTest.kt
> +        composeTestRule.onNodeWithText(str(R.string.auth_title)).performClick()
Indeed, good catch

2023-03-29 00:57 UTC, NervzZ approved these changes
LGTM now

2023-03-29 00:57 UTC, merged