Feature/issue 4
studhub-epfl/studhub-app pull request #78
Opened 2023-03-28 20:21 UTC by tepoorte

2023-03-28 22:43 UTC, edouardmichelin requested changes
Added a few comments with some changes requested.
Also don't forget to add tests (min 80% coverage required)

2023-03-28 22:43 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +            //val retrievedListing: Listing? = query.result.getValue(Listing::class.java)
Remove unused comment

2023-03-28 22:43 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/domain/usecase/listing/GetListingsBySearch.kt
> + * Use case for getting all listings from a given [repository]
Documentation does not match the actual behavior. We are not getting **all** listings, only the ones matching a given keyword

2023-03-28 22:47 UTC, edouardmichelin requested changes

2023-03-28 22:47 UTC, edouardmichelin commented on app/src/main/java/com/studhub/app/domain/usecase/listing/GetListingsBySearch.kt
> +    }
I think you should check that the keyword has a minimal length (either here or enforce it in the repository implementation.
3 characters seems to be a good minimal length but tell me if you think otherwise.

2023-03-29 12:23 UTC, raynasr commented on app/src/main/java/com/studhub/app/domain/usecase/listing/GetListingsBySearch.kt
> +    }
Good idea

2023-03-29 19:50 UTC, tepoorte commented on app/src/main/java/com/studhub/app/data/repository/ListingRepositoryImpl.kt
> +            }
I think your code is more "politically correct" and respect the convention. Actually the id should not be checked as you said, by the way using filter can be clearer and more readable, since the filter condition is defined more declaratively while the second code uses a more imperative approach.  But in the end I think that using "contains" is the correct approach compared to == as you said! Thank you very much!

2023-03-29 19:53 UTC, tepoorte commented on app/src/main/java/com/studhub/app/domain/usecase/listing/GetListingsBySearch.kt
> +    }
That's a good point!

2023-03-30 20:24 UTC, edouardmichelin approved these changes
Everything now seems to be alright.

2023-03-30 20:28 UTC, raynasr approved these changes
LGTM Now.

2023-03-30 20:29 UTC, merged