Add the favorite feature to the listing view
studhub-epfl/studhub-app pull request #87
Opened 2023-03-31 07:44 UTC by Edouard-6

2023-04-20 22:40 UTC, NervzZ requested changes
Need to add test and also figure out why it's not passing the automated testing. I find a bit surprising that no method needs to be passed for the favorite button as it may make things less generic and maybe some other already existing composables could have been used instead.

2023-04-27 15:02 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingScreen.kt
>  package com.studhub.app.presentation.listing.details
I don't see where you implement the favorite button in the screen?

2023-04-27 15:04 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingViewModel.kt
> +import kotlinx.coroutines.flow.MutableSharedFlow
Duplicate import statements

2023-04-27 15:05 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/listing/details/DetailedListingViewModel.kt
> +                    getFavoriteListings().collect {
import kotlinx.coroutines.flow.collect missing

2023-04-27 15:06 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/listing/details/components/FavoriteButton.kt
> +
Remove this useless import

2023-04-27 15:07 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/listing/details/components/FavoriteButton.kt
> +import androidx.compose.material3.Icon
Replace with androidx.compose.material3.icons.Icons

2023-04-27 15:07 UTC, raynasr requested changes
Import statements to fix. LGTM.

2023-05-04 20:43 UTC, raynasr approved these changes

2023-05-05 02:13 UTC, closed without merging