Feature/issue 94
studhub-epfl/studhub-app pull request #99
Opened 2023-04-20 02:31 UTC by raynasr

Need someone with a working emulator to navigation to the RatingScreen using the following composable:
        composable("RatingScreen") {
            UserRatingScreen(targetUserId = "-NQSUz5EY7-EfBG7PCIu")
        }
And report what you see

2023-04-20 23:08 UTC, NervzZ requested changes
Please make the requested changes and make sure the automated testing passes.

Good job on adding your tests though!

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/domain/usecase/user/AddRating.kt
> +}
Same as some previous comments, would probably be cleaner as separate use cases independent of user. Have those in domain/usecase/review/...

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/domain/usecase/user/DeleteRating.kt
> +package com.studhub.app.domain.usecase.user
Same as some previous comments, would probably be cleaner as separate use cases independent of user. Have those in domain/usecase/review/...

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/domain/usecase/user/GetUserRatings.kt
> +package com.studhub.app.domain.usecase.user
Same as some previous comments, would probably be cleaner as separate use cases independent of user. Have those in domain/usecase/review/...

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/domain/usecase/user/UpdateRating.kt
> +package com.studhub.app.domain.usecase.user
Same as some previous comments, would probably be cleaner as separate use cases independent of user. Have those in domain/usecase/review/...

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/ratings/IUserRatingViewModel.kt
> +interface IUserRatingViewModel {
Why the "I" in front for the naming?

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/ratings/UserRatingScreen.kt
> +}
We talked about this before, you can't have infinite sized composables like this for the sake of readability. Please modularize this at the best of your capacity to make it more concise, readable and more importantly maintainable when someone else works on your code.

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/ratings/components/RatingItem.kt
> +fun RatingItem(
Might just want to call this RatingButton instead and please user as much as possible already existing composables.

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/presentation/ui/CommonPreview.kt
> +
Reformat to remove unecessary spaces.

2023-04-20 23:08 UTC, NervzZ commented on app/src/main/java/com/studhub/app/wrapper/RatingActivity.kt
> +class RatingActivity : AppCompatActivity(){
Since we're using screens now, we shouldn't use activities like this anymore. Instead create a RatingScreen and add the route in the navigation like it has been done for pretty much every other views. It shouldn't be hard to add new screens this way.

2023-04-21 00:03 UTC, raynasr commented on app/src/main/java/com/studhub/app/MainActivity.kt
> -    private fun handleLoginComplete() = navController.navigate("Home")
Testing purposes, will be reverted.

2023-04-21 00:03 UTC, raynasr commented on app/src/main/java/com/studhub/app/NavigationComponent.kt
> -                        navController.navigate("Home")
Testing purposes, will be reverted.

2023-04-21 00:04 UTC, raynasr commented on app/src/main/java/com/studhub/app/NavigationComponent.kt
> +            UserRatingScreen(targetUserId = "-NQSUz5EY7-EfBG7PCIu")
Testing purposes, will be reverted.

2023-04-21 00:04 UTC, raynasr commented on app/src/main/java/com/studhub/app/data/repository/UserRepositoryImpl.kt
> +
I do not share this feeling as of yet.

2023-04-21 00:04 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/ratings/IUserRatingViewModel.kt
> +interface IUserRatingViewModel {
Interface

2023-04-21 00:05 UTC, raynasr commented on app/src/main/java/com/studhub/app/domain/model/Rating.kt
> +    val thumbDown: Boolean = false,
They make since, they are used in a checkbox system where no two checkboxes can be checked twice. Either up or down.
userId because it's a user's ratings. seller works but all the use cases like "getUser" and "getCurrentUser" refers to a "user" so to avoid confusion I went with userId. reviewId leaves no ambiguity.

2023-04-27 15:21 UTC, Edouard-6 requested changes
Tests are missing. Otherwise, LGTM.

2023-04-27 15:21 UTC, Edouard-6 commented on app/src/androidTest/java/com/studhub/app/domain/usecase/UserUseCaseTest.kt
Same for here. Why the methods are not implemented?

2023-04-27 15:21 UTC, Edouard-6 commented on app/src/main/java/com/studhub/app/NavigationComponent.kt
> +            UserRatingScreen(targetUserId = "-NRpD74U8sedQAH5_hdn")
Why is the targetUserId hardcoded? If you need this specific Id add it in the strings.xml, otherwise use the random strings to generate it.

2023-05-02 12:15 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/ratings/components/RatingItem.kt
> +) {
The screen code has been modularization as much as possible. As to the components (composables) it uses, length isn't a problem in and of itself. Seperating the RatingItem into many composables doesn't make sense on a modular level, and would create more unnecessary lambda function calls.

2023-05-02 12:15 UTC, raynasr commented on app/src/androidTest/java/com/studhub/app/data/repository/MockUserRepositoryImpl.kt
> +
They will be implemented by Sam in the testing task.

2023-05-02 12:16 UTC, raynasr commented on app/src/main/java/com/studhub/app/presentation/ratings/UserRatingScreen.kt
> +}
Please refer to the newest commit for changes related to modularity (this nightmare is no longer there). Thank you.

2023-05-05 07:10 UTC, NervzZ approved these changes
Approved because it's necessary for the meeting's demo

2023-05-05 07:21 UTC, Edouard-6 approved these changes

2023-05-05 07:22 UTC, Edouard-6 approved these changes
LGTM.

2023-05-09 13:40 UTC, merged